### PR TITLE
Full test coverage for Magnet project

### PR DESCRIPTION
**Pull request by furknyavuz**
Hi @premnirmal,

I'm happy to say that I fully covered test cases for Magnet project.

This pull request is raise the overall coverage of the project to 80%.
I also added CODE_COVERAGE.md file to give informations about generating code coverage.

Please let me know if you have any questions.

Furkan Yavuz
DevFactory - Code Quality Team

### CODE REVIEW

**Comment by premnirmal** [comment]
Thanks @furknyavuz

**Comment by premnirmal** [comment]
Can you add the build/test to `circle.yml`? That way I can see the test coverage in the circle artifacts. 

Something like:
**circle.yml**
``` yml
test:
  pre:
    - ./gradlew lint
  override:
    - ./gradlew build
    - ./gradlew jacocoTestReport
    - cp -r demo/build/outputs $CIRCLE_ARTIFACTS
    - cp -r library/build/reports/ $CIRCLE_TEST_REPORTS
```

**Comment by furknyavuz** [comment]
Hey @premnirmal,

I added your requested lines to .yml file.

**Comment by premnirmal** [comment]
The test coverage report shows 3% coverage: https://circle-artifacts.com/gh/premnirmal/Magnet/11/artifacts/0/tmp/circle-junit.lh9DU60/jacoco/jacocoTestDebugUnitTestReport/html/index.html
Or am I reading the wrong file?

**Comment by furknyavuz** [comment]
Hi @premnirmal,

Let me investigate this problem. I'll ping you again after solving this issue.

Thanks,

**Comment by furknyavuz** [comment]
Ok, I solved the problem via changing jacoco plugin to cobertura.

Now I can see %75 ratio, but still we need to exclude some generated files to see real coverage ratio.

**Comment by premnirmal** [comment]
Looks good, thanks!

**Comment by furknyavuz** [comment]
You'r welcome!!

**Pull request merged**
